# Generated by Django 5.1.1 on 2024-09-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googleMaps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
